In [ ]:
# arr = ['10:15','3:6', '8:10', '1:2', '16.3:17'] # 10:18:10:18
# def sort_merge(arr):
#     bool = False
# #sorting 
#     # for i in range(len(arr)-1):
#     #     if(int(arr[i][0])>int(arr[i+1][0]) or (int(arr[i][0])==int(arr[i+1][0]) and int(arr[i][2:4])>int(arr[i+1][2:4]))):
#     #         arr[i], arr[i+1] =  arr[i+1], arr[i]
#     #         bool=True
#     #     else: 
#     #         bool=False 
#     #     while(bool and i > 0):
#     #         if(int(arr[i][0])<int(arr[i-1][0]) or (int(arr[i][0])==int(arr[i-1][0]) and int(arr[i][2:4])<int(arr[i-1][2:4]))):
#     #             arr[i-1], arr[i] =  arr[i], arr[i-1]
#     #         else: 
#     #             bool=False 
#     i = 0 
#     while(i < (len(arr)-1)):
#         print(i)
#         a,b =  arr[i].split(':')
#         c,d = arr[i+1].split(':') 
#         if(float(a)>float(c) or (float(a)==float(c) and float(b)>float(d))): 
#             arr[i], arr[i+1] =  arr[i+1], arr[i]
#             bool=True
#         else: 
#             bool=True
#         # while(bool and i>1): 
#         #     e,f = arr[i-1].split(':')
#         #     if(float(a)<float(e) or  (float(a)==float(e) and float(b)<float(f))): 
#         #         arr[i-1], arr[i] =  arr[i], arr[i-1]
#         #         i -= 2
#         #     else: 
#         #         bool = False 
#         i += 1 
        
            
# sort_merge(arr)
# print(arr)  


# #merging 
#     # for i in range(len(arr)-1):
#     #     if(int()): 



In [123]:
# import numpy as np 
# arr = ['10:15','3:6', '1.8:3', '8:10', '1:2', '16.3:17'] 
# length = 21.6 
# duration = 2
# #sort 
# a = np.array([])
# for i in range(len(arr)):
#     x,y =  arr[i].split(':')
#     x,y =  float(x), float(y) 
#     a = np.append(a, [x,y])
# a = np.reshape(a, (-1,2))

# #a = a[a[:, 0].argsort()]

# #merge

# i = 0  
# while(i < len(a[:,0])-1):
#     if(a[(i+1),0]<=a[(i),1]): #if start is greater than end of  previous interval 
#         a[i,1] = a[i+1,1]
#         a = np.delete(a, i+1, 0)
#         #a = np.delete(a, a[i+1],)
#     else: 
#         i  += 1
# print(a)

# #clip 
# clip = []
# start = 0 
# for i in  range(len(a[:,0])):
#     clip.append(start)
#     clip.append(a[i,0])
#     start = a[i,1]
# clip.append(start)
# clip.append(length)
# # i = 0 
# # while(i < (len(clip)-1)): 
# #     if((clip[i+1]-clip[i])<duration): 
# #         clip.remove(clip[i])
# #         clip.remove(clip[i+1])
# #     i+=1
# # print(clip)
# clip = np.array([clip])
# clip = np.reshape(clip, (-1,2))
# print(clip)
# #delete clips less than duration 

[[10.   3. ]
 [ 8.   2. ]
 [16.3 17. ]]
[[ 0.  10. ]
 [ 3.   8. ]
 [ 2.  16.3]
 [17.  21.6]]


In [1]:
# import numpy as np 

# arr = [[10.0, 15.0], [3.0,3.5],  [1.8, 3.0], [8.0, 10.0], [1.0,  2.0], [16.3, 17.0]]
# duration = 4 
# length = 24.31 
# N = 20
# step = 0.1 
# arr = np.sort(arr, axis=0) # sort the array along the 0th axis (rows)
# print(arr)  # Output: [[ 1.  2.]
# i = 0  
# while(i < len(arr[:,0])-1):
#     if(arr[(i+1),0]<=arr[(i),1]): #if start is greater than end of  previous interval 
#         arr[i,1] = arr[i+1,1]
#         arr = np.delete(arr, i+1, 0)
#         #a = np.delete(a, a[i+1],)
#     else: 
#         i  += 1
# print(arr)
# #create windows

[[ 1.   2. ]
 [ 1.8  3. ]
 [ 3.   3.5]
 [ 8.  10. ]
 [10.  15. ]
 [16.3 17. ]]
[[ 1.   3.5]
 [ 8.  15. ]
 [16.3 17. ]]


In [25]:
'''start = 0 
windows = []
for i in range (len(arr[:,0])):
    windows.append(arr[i,0]-start)
    windows.append(start)
    windows.append(arr[i,0])
    start = arr[i,1]
    if(i  == len(arr[:,0])-1):
        windows.append(length-arr[-1,1])
        windows.append(arr[-1,1])
        windows.append(length)

windows = np.array(windows)
windows = np.reshape(windows, (-1,3))
windows = windows[windows[:,0].argsort()]

arr: 
[[ 1.   3.5]
 [ 8.  15. ]
 [16.3 17. ]]
'''

[[ 1.    0.    1.  ]
 [ 1.3  15.   16.3 ]
 [ 4.5   3.5   8.  ]
 [ 7.31 17.   24.31]]


In [18]:

'''
while(i < len(windows[:,0])):
    if(windows[i,0] >= duration):
        max = ((windows[i,0])-duration)/step + 1
        sum += max
        MaxPossible.append(max)
        i  += 1
    else: 
        windows =  np.delete(windows, i, axis=0)
'''
'''
for i in range(len(MaxPossible)):
    p = N*MaxPossible[i]/sum 
    proportional.append(p)
    
#output: proportional [2.9925187032418963, 17.007481296758105]

# for i in range(len(proportional)): 
#     steps.append((windows[i,0]-duration)/proportional[i])#proportional to step value 
# print('step size', steps)   
#new array with  the new values

# x = 0  
# while(x < len(windows[:,0])): 
#     w = int(proportional[x] + 1)
#     w = w if w < remaining else remaining 
#     remaining -= w 
#     new_step =  (windows[x,0]-duration)/(w-1)
#     start = windows[x,1]
#     for i in range(w):
#        valid_clips.append(truncate_float(start, 3))
#        start = windows[x, 2] - duration if i == w - 1 else start + new_step            
#     x +=1
# assert len(valid_clips) == N 

# for x in range(len(windows[:, 0])):
#     w = min(int(proportional[x] + 1), remaining)  # Get w directly using min
#     remaining -= w 
#     new_step = (windows[x, 0] - duration) / (w - 1) if w > 1 else 0  # Avoid division by zero

#     start = windows[x, 1]
#     for i in range(w):
#         valid_clips.append(truncate_float(start, 3))
#         start = windows[x, 2] - duration if i == w - 1 else start + new_step 
'''
       
    
#validate a lot of the code, optimize (get rid of arrays and reduce  complexity) 


windows [[ 4.5   3.5   8.  ]
 [ 7.31 17.   24.31]]
new [[ 4.5   3.5   8.  ]
 [ 7.31 17.   24.31]]
MaxPossible [ 6.  34.1]
proportional [2.9925187032418963, 17.007481296758105]
valid_clips 20 [3.5, 3.75, 4.0, 17.0, 17.206, 17.413, 17.62, 17.827, 18.034, 18.241, 18.448, 18.655, 18.861, 19.068, 19.275, 19.482, 19.689, 19.896, 20.103, 20.31]


In [45]:
import numpy as np 

arr = [[10.0, 15.0], [3.0,3.5],  [1.8, 3.0], [8.0, 10.0], [1.0,  2.0], [16.3, 17.0]]
arr = np.sort(arr, axis=0)
print('Initial Input defects\n', arr)

duration, length, N, min_step = 4, 24.31, 20, 0.1
windows, MaxPossible, valid_clips = [],[],[]
remaining = N 

#combine
i = 0
while i < len(arr[:, 0]) - 1:
    arr[i, 1] = arr[i + 1, 1] if arr[i + 1, 0] <= arr[i, 1] else arr[i, 1]
    arr = np.delete(arr, i + 1, 0) if arr[i + 1, 0] <= arr[i, 1] else arr
    i += 1 if arr[i + 1, 0] > arr[i, 1] else 0
#windows
for i in range (len(arr[:,0])):
    start = 0 if  i == 0 else arr[i-1,1]
    windows.extend([arr[i,0]-start, start, arr[i,0]])
    windows.extend([length-arr[-1,1],  arr[-1,1], length]) if i  == len(arr[:,0])-1 else []
windows = np.reshape(np.array(windows), (-1,3))
windows = windows[(windows)[:,0].argsort()]

#new, MaxPossible, proportional 
new = np.squeeze(windows[np.argwhere(windows[:,0]>=duration)])
MaxPossible = (((new[:,0][np.argwhere(first>=duration)] - duration) / min_step + 1)).flatten()
proportional = [N*i/(np.sum(MaxPossible)) for i in MaxPossible]
#validclips 
assert  len(new[:,0]) == len(MaxPossible) == len(proportional)

for x in range(len(new[:,0])):
    w = int(proportional[x] + 1) if int(proportional[x] + 1) < remaining else remaining 
    remaining -= w 
    new_step = (new[x,0]-duration)/ (w - 1) if w > 1 else 0  # Avoid division by zero
    start = new[x,1]
    for i in range(w):
        valid_clips.append(int(start * 10 ** 3) / 10 ** 3)
        start = new[x,2] - duration if i == w - 1 else start + new_step
assert  len(valid_clips) == N , f"Expected {N} valid clips, but got {len(valid_clips)}"


print('Input defects\n', arr)
print('windows\n', windows)
print('new\n', new)    
print('MaxPossible\n', MaxPossible)
print('proportional\n', proportional)
print('valid_clips\n', len(valid_clips), valid_clips)


Initial Input defects
 [[ 1.   2. ]
 [ 1.8  3. ]
 [ 3.   3.5]
 [ 8.  10. ]
 [10.  15. ]
 [16.3 17. ]]
Input defects
 [[ 1.   3.5]
 [ 8.  15. ]
 [16.3 17. ]]
windows
 [[ 1.    0.    1.  ]
 [ 1.3  15.   16.3 ]
 [ 4.5   3.5   8.  ]
 [ 7.31 17.   24.31]]
new
 [[ 4.5   3.5   8.  ]
 [ 7.31 17.   24.31]]
MaxPossible
 [ 6.  34.1]
proportional
 [2.9925187032418963, 17.007481296758105]
valid_clips
 20 [3.5, 3.75, 4.0, 17.0, 17.206, 17.413, 17.62, 17.827, 18.034, 18.241, 18.448, 18.655, 18.861, 19.068, 19.275, 19.482, 19.689, 19.896, 20.103, 20.31]
